version: 0.2

env:
  shell: bash
  variables:
    XD: "XDDD"
    ABC: "DEF"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.9
    commands:
      - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      - ls
      - ls -al ~/
      - ls -al $HOME
      - source $HOME/.cargo/env
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Pre Build!"
      - ls
      - pwd
      - env
      - cargo help
  build:
    on-failure: ABORT
    commands:
      - echo "Build!!"
      - python a.py
      - cargo build --release
      - cp target/release/binary-run ./binary-run
  post_build:
    on-failure: ABORT
    commands:
      - echo "Post Build!!!"
# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no | yes
#     file-format: report-format
artifacts:
  files:
    - binary-run
  name: runThis
  discard-paths: yes
  # base-directory: ~/
  enable-symlinks: no
  s3-prefix: prefix